# Generated by Django 5.0 on 2024-02-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctrated', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=18)),
                ('lastname', models.CharField(max_length=18)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=18)),
                ('city', models.CharField(max_length=18)),
                ('state', models.CharField(max_length=18)),
                ('mobile', models.CharField(max_length=18)),
            ],
        ),
    ]
