# Generated by Django 5.0 on 2024-02-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_Appp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctrated', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=18)),
                ('cate', models.CharField(max_length=18)),
                ('myfile', models.FileField(upload_to='Notes_errors')),
                ('desc', models.TextField()),
            ],
        ),
    ]
