# Generated by Django 5.0 on 2024-02-14 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('M_Appp', '0003_feedbachmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedbachModel',
            new_name='feedbackModel',
        ),
    ]
